# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 spatterlight
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
# SPDX-FileCopyrightText: 2026 sudo-Tiz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Bazarr systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ bazarr_identifier }}.service"
  register: bazarr_service_stat

- name: Uninstall Bazarr systemd services and files
  when: bazarr_service_stat.stat.exists | bool
  block:
    - name: Ensure Bazarr systemd service is stopped
      ansible.builtin.service:
        name: "{{ bazarr_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Bazarr systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ bazarr_identifier }}.service"
        state: absent

    - name: Ensure Bazarr support files do not exist
      ansible.builtin.file:
        path: "{{ bazarr_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure Bazarr local data path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ bazarr_data_path }}"
      register: bazarr_data_path_deletion_result
      changed_when: bazarr_data_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Bazarr base path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ bazarr_base_path }}"
      register: bazarr_base_path_deletion_result
      changed_when: bazarr_base_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Bazarr container network does not exist
      when: bazarr_container_network_deletion_enabled
      block:
        - name: Ensure Bazarr container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ bazarr_container_network }}"
            state: absent
          register: bazarr_network_deletion_result

        - name: Ensure Bazarr container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ bazarr_container_network }}
          register: bazarr_network_deletion_result
          changed_when: bazarr_container_network in bazarr_network_deletion_result.stdout

- name: Check existence of Bazarr local data path
  ansible.builtin.stat:
    path: "{{ bazarr_data_path }}"
  register: bazarr_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Inject the message about the remaining Bazarr local data path
  when: bazarr_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Bazarr instance has been removed, some old data remains in `" + bazarr_data_path + "`. Feel free to delete it."
        ]
      }}
